# Site settings
title: "Off-Label Use"
email: chris.dukes.aix@gmail.com
description: "Chris Dukes Technology Blog"
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
# Other
tag_title_prefix: '&ldquo;'
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
