# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris Dukes
email: chris.dukes.aix@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sysadmin, programmer, farmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  cdd-aix

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
minima:
  date_format: '%Y %b %d'
plugins:
  - github-pages
  - jekyll
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - about.md
  - posts.md
  - TODO.md
  - resumes.md

permalink: pretty

collections:
  resumes:
    output: true
    title: Resumes

  TODO:
    output: true
    title: TODO

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
