# Site settings
title: "Off-Label Use"
email: chris.dukes.aix@gmail.com
description: "Chris Dukes Technology Blog"
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
github_username:  cdd-aix

# Build settings
markdown: kramdown
permalink: pretty
# Other
collections:
  TODO:
    output: true

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "TODO"
    values:
      layout: "page"
